import type { NextPage } from "next";
import { useEffect } from "react";
import AOS from "aos";
import "aos/dist/aos.css";
import Head from "next/head";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Sertifikat from "../components/Sertifikat";
import Contact from "../components/Contact";
import Main from "./../components/Main";
import About from "../components/About";

const Home: NextPage = () => {
  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <div className="">
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <About />
      <Main />
      <Skills />
      <Projects />
      <Sertifikat />
      <Contact />
    </div>
  );
};

export default Home;
